package utils

import go_ora "github.com/sijms/go-ora/v2"

func SwitchToGoOraType(typeName string) go_ora.OracleType {
	switch typeName {
	case "NCHAR":
		return go_ora.NCHAR
	case "NUMBER":
		return go_ora.NUMBER
	case "SB1":
		return go_ora.SB1
	case "SB2":
		return go_ora.SB2
	case "SB4":
		return go_ora.SB4
	case "FLOAT":
		return go_ora.FLOAT
	case "NullStr":
		return go_ora.NullStr
	case "VarNum":
		return go_ora.VarNum
	case "LONG":
		return go_ora.LONG
	case "VARCHAR":
		return go_ora.VARCHAR
	case "ROWID":
		return go_ora.ROWID
	case "DATE":
		return go_ora.DATE
	case "VarRaw":
		return go_ora.VarRaw
	case "BFloat":
		return go_ora.BFloat
	case "BDouble":
		return go_ora.BDouble
	case "RAW":
		return go_ora.RAW
	case "LongRaw":
		return go_ora.LongRaw
	case "UINT":
		return go_ora.UINT
	case "LongVarChar":
		return go_ora.LongVarChar
	case "LongVarRaw":
		return go_ora.LongVarRaw
	case "CHAR":
		return go_ora.CHAR
	case "CHARZ":
		return go_ora.CHARZ
	case "IBFloat":
		return go_ora.IBFloat
	case "IBDouble":
		return go_ora.IBDouble
	case "REFCURSOR":
		return go_ora.REFCURSOR
	case "OCIXMLType":
		return go_ora.OCIXMLType
	case "XMLType":
		return go_ora.XMLType
	case "OCIRef":
		return go_ora.OCIRef
	case "OCIClobLocator":
		return go_ora.OCIClobLocator
	case "OCIBlobLocator":
		return go_ora.OCIBlobLocator
	case "OCIFileLocator":
		return go_ora.OCIFileLocator
	case "ResultSet":
		return go_ora.ResultSet
	case "OCIString":
		return go_ora.OCIString
	case "OCIDate":
		return go_ora.OCIDate
	case "TimeStampDTY":
		return go_ora.TimeStampDTY
	case "TimeStampTZ_DTY":
		return go_ora.TimeStampLTZ_DTY
	case "IntervalYM_DTY":
		return go_ora.IntervalYM_DTY
	case "IntervalDS_DTY":
		return go_ora.IntervalDS_DTY
	case "TimeTZ":
		return go_ora.TimeTZ
	case "TIMESTAMP":
		return go_ora.TIMESTAMP
	case "TimeStampTZ":
		return go_ora.TimeStampTZ
	case "IntervalYM":
		return go_ora.IntervalYM
	case "IntervalDS":
		return go_ora.IntervalDS
	case "UROWID":
		return go_ora.UROWID
	case "TimeStampLTZ_DTY":
		return go_ora.TimeStampLTZ_DTY
	case "TimeStampeLTZ":
		return go_ora.TimeStampeLTZ
	}
	return go_ora.VARCHAR
}
